# Database Configuration
datasource.url=jdbc:postgresql://localhost:5432/postgres
datasource.username=postgres
datasource.password=ravi
datasource.driver-class-name=org.postgresql.Driver

# Poller Configuration
poller.interval=60s

