#server.address=0.0.0.0

#timeout values
connection.timeout=20
response.timeout=20
connection.request.timeout=20
healthcheck.cron=0 0/1 * * * *

spring.main.banner-mode=OFF
server.port=9092
server.servlet.context-path= /service-pulse-app
spring.application.name = service-pulse-app
spring.datasource.url=jdbc:mysql://192.168.29.84:3306/service-pulse-app
spring.datasource.username=ravi
spring.datasource.password=ravi
spring.jmx.enabled = true
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.maximum-pool-size=30000
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
logging.level.org.hibernate.SQL=DEBUG
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ssZ
spring.main.allow-bean-definition-overriding=true
spring.main.allow-circular-references=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.shutdown.enabled=true
management.info.env.enabled=true