name: Microservice Build Pipeline

on:
  push:
    branches: ["master"]

jobs:
  build-and-deploy:
    # Point this to your central hub repository
    uses: rsp777/deployment-workflows/.github/workflows/maven-build.yml@main
    permissions:
      contents: write # Allow pushing commits/tags
      packages: write # Allow publishing packages
    # 1. 'with' is used for public strings and GitHub context variables
    with:
      USERNAME: ${{ github.actor }}

    # 2. 'secrets' is used ONLY for secure tokens
    secrets:
      PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      REPO_URL: ${{ secrets.REPO_URL }}
      REPO_NAME: ${{ secrets.REPO_NAME }}

  docker-build-push:
    needs: build-and-deploy
    # Point this to your central hub repository
    uses: rsp777/deployment-workflows/.github/workflows/docker-build-deploy.yml@main
    permissions:
      contents: write # Allow pushing commits/tags
      packages: write # Allow publishing packages
    # 1. 'with' is used for public strings and GitHub context variables
    with:
      USERNAME: ${{ github.actor }}
      # FIX: Use GitHub's built-in variables instead of custom secrets
      REPO_NAME: ${{ github.event.repository.name }}
      REPO_URL: ${{ github.server_url }}/${{ github.repository }}
    # 2. 'secrets' is used ONLY for secure tokens
    secrets:
      PASSWORD: ${{ secrets.GITHUB_TOKEN }}
     
